[package]
name = "drop-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
base64ct = { version = "1.0.1", features = ["alloc"] }
sha2 = { version = "0.10.5" }
merkle_light = { version = "0.4.0" }
merkle_light_derive = { version = "0.4.0" }
